/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */
#include <stdlib.h> /* for srand() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */

	srand( (unsigned)time(NULL) );

	globalArgc = argc;
	globalArgv = argv;

#ifndef OMITGOOD

	/* Calling C good functions */
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */


	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_01_good();");
	CWE190_Integer_Overflow__char_fscanf_square_01_good();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_02_good();");
	CWE190_Integer_Overflow__char_fscanf_square_02_good();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_03_good();");
	CWE190_Integer_Overflow__char_fscanf_square_03_good();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_04_good();");
	CWE190_Integer_Overflow__char_fscanf_square_04_good();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_05_good();");
	CWE190_Integer_Overflow__char_fscanf_square_05_good();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_06_good();");
	CWE190_Integer_Overflow__char_fscanf_square_06_good();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_07_good();");
	CWE190_Integer_Overflow__char_fscanf_square_07_good();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_08_good();");
	CWE190_Integer_Overflow__char_fscanf_square_08_good();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_09_good();");
	CWE190_Integer_Overflow__char_fscanf_square_09_good();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_10_good();");
	CWE190_Integer_Overflow__char_fscanf_square_10_good();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_11_good();");
	CWE190_Integer_Overflow__char_fscanf_square_11_good();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_12_good();");
	CWE190_Integer_Overflow__char_fscanf_square_12_good();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_13_good();");
	CWE190_Integer_Overflow__char_fscanf_square_13_good();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_14_good();");
	CWE190_Integer_Overflow__char_fscanf_square_14_good();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_15_good();");
	CWE190_Integer_Overflow__char_fscanf_square_15_good();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_16_good();");
	CWE190_Integer_Overflow__char_fscanf_square_16_good();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_17_good();");
	CWE190_Integer_Overflow__char_fscanf_square_17_good();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_18_good();");
	CWE190_Integer_Overflow__char_fscanf_square_18_good();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_21_good();");
	CWE190_Integer_Overflow__char_fscanf_square_21_good();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_22_good();");
	CWE190_Integer_Overflow__char_fscanf_square_22_good();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_31_good();");
	CWE190_Integer_Overflow__char_fscanf_square_31_good();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_32_good();");
	CWE190_Integer_Overflow__char_fscanf_square_32_good();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_34_good();");
	CWE190_Integer_Overflow__char_fscanf_square_34_good();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_41_good();");
	CWE190_Integer_Overflow__char_fscanf_square_41_good();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_42_good();");
	CWE190_Integer_Overflow__char_fscanf_square_42_good();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_44_good();");
	CWE190_Integer_Overflow__char_fscanf_square_44_good();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_45_good();");
	CWE190_Integer_Overflow__char_fscanf_square_45_good();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_51_good();");
	CWE190_Integer_Overflow__char_fscanf_square_51_good();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_52_good();");
	CWE190_Integer_Overflow__char_fscanf_square_52_good();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_53_good();");
	CWE190_Integer_Overflow__char_fscanf_square_53_good();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_54_good();");
	CWE190_Integer_Overflow__char_fscanf_square_54_good();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_61_good();");
	CWE190_Integer_Overflow__char_fscanf_square_61_good();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_63_good();");
	CWE190_Integer_Overflow__char_fscanf_square_63_good();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_64_good();");
	CWE190_Integer_Overflow__char_fscanf_square_64_good();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_65_good();");
	CWE190_Integer_Overflow__char_fscanf_square_65_good();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_66_good();");
	CWE190_Integer_Overflow__char_fscanf_square_66_good();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_67_good();");
	CWE190_Integer_Overflow__char_fscanf_square_67_good();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_68_good();");
	CWE190_Integer_Overflow__char_fscanf_square_68_good();


	/* END-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */

#endif /* OMITGOOD */

#ifndef OMITBAD

	/* Calling C bad functions */
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-CALLS */


	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_01_bad();");
	CWE190_Integer_Overflow__char_fscanf_square_01_bad();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_02_bad();");
	CWE190_Integer_Overflow__char_fscanf_square_02_bad();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_03_bad();");
	CWE190_Integer_Overflow__char_fscanf_square_03_bad();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_04_bad();");
	CWE190_Integer_Overflow__char_fscanf_square_04_bad();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_05_bad();");
	CWE190_Integer_Overflow__char_fscanf_square_05_bad();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_06_bad();");
	CWE190_Integer_Overflow__char_fscanf_square_06_bad();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_07_bad();");
	CWE190_Integer_Overflow__char_fscanf_square_07_bad();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_08_bad();");
	CWE190_Integer_Overflow__char_fscanf_square_08_bad();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_09_bad();");
	CWE190_Integer_Overflow__char_fscanf_square_09_bad();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_10_bad();");
	CWE190_Integer_Overflow__char_fscanf_square_10_bad();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_11_bad();");
	CWE190_Integer_Overflow__char_fscanf_square_11_bad();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_12_bad();");
	CWE190_Integer_Overflow__char_fscanf_square_12_bad();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_13_bad();");
	CWE190_Integer_Overflow__char_fscanf_square_13_bad();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_14_bad();");
	CWE190_Integer_Overflow__char_fscanf_square_14_bad();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_15_bad();");
	CWE190_Integer_Overflow__char_fscanf_square_15_bad();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_16_bad();");
	CWE190_Integer_Overflow__char_fscanf_square_16_bad();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_17_bad();");
	CWE190_Integer_Overflow__char_fscanf_square_17_bad();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_18_bad();");
	CWE190_Integer_Overflow__char_fscanf_square_18_bad();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_21_bad();");
	CWE190_Integer_Overflow__char_fscanf_square_21_bad();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_22_bad();");
	CWE190_Integer_Overflow__char_fscanf_square_22_bad();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_31_bad();");
	CWE190_Integer_Overflow__char_fscanf_square_31_bad();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_32_bad();");
	CWE190_Integer_Overflow__char_fscanf_square_32_bad();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_34_bad();");
	CWE190_Integer_Overflow__char_fscanf_square_34_bad();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_41_bad();");
	CWE190_Integer_Overflow__char_fscanf_square_41_bad();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_42_bad();");
	CWE190_Integer_Overflow__char_fscanf_square_42_bad();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_44_bad();");
	CWE190_Integer_Overflow__char_fscanf_square_44_bad();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_45_bad();");
	CWE190_Integer_Overflow__char_fscanf_square_45_bad();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_51_bad();");
	CWE190_Integer_Overflow__char_fscanf_square_51_bad();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_52_bad();");
	CWE190_Integer_Overflow__char_fscanf_square_52_bad();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_53_bad();");
	CWE190_Integer_Overflow__char_fscanf_square_53_bad();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_54_bad();");
	CWE190_Integer_Overflow__char_fscanf_square_54_bad();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_61_bad();");
	CWE190_Integer_Overflow__char_fscanf_square_61_bad();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_63_bad();");
	CWE190_Integer_Overflow__char_fscanf_square_63_bad();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_64_bad();");
	CWE190_Integer_Overflow__char_fscanf_square_64_bad();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_65_bad();");
	CWE190_Integer_Overflow__char_fscanf_square_65_bad();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_66_bad();");
	CWE190_Integer_Overflow__char_fscanf_square_66_bad();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_67_bad();");
	CWE190_Integer_Overflow__char_fscanf_square_67_bad();

	printLine("Calling CWE190_Integer_Overflow__char_fscanf_square_68_bad();");
	CWE190_Integer_Overflow__char_fscanf_square_68_bad();

	/* END-AUTOGENERATED-C-BAD-FUNCTION-CALLS */


#endif /* OMITBAD */

	return 0;

} 
