deletion_of_data_structure_sentinel: deletion_of_data_structure_sentinel.o deletion_of_data_structure_sentinel_main.o
	gcc deletion_of_data_structure_sentinel.o deletion_of_data_structure_sentinel_main.o -lm -lpthread -o deletion_of_data_structure_sentinel
 
deletion_of_data_structure_sentinel.o: deletion_of_data_structure_sentinel.c
	gcc -c deletion_of_data_structure_sentinel.c -o deletion_of_data_structure_sentinel.o
 
deletion_of_data_structure_sentinel_main.o: deletion_of_data_structure_sentinel_main.c
	gcc -c deletion_of_data_structure_sentinel_main.c -o deletion_of_data_structure_sentinel_main.o
 
clean:
	rm -f *.o
	rm -f deletion_of_data_structure_sentinel
